@startuml
!include <C4/C4_Component>

Container(web_app, "Web Application", "React")

Component(App, "App", "React Component")
Component(Header, "Header", "React Component")
Component(Menu, "Menu", "React Component")
Component(Foter, "Footer", "React Component")
Component(Pizza, "Pizza", "React Component")
Component(Order, "Order", "React Component")
ComponentDb(PizzaData, "Pizza Data", "")

Rel(App, Header, "Renders")
Rel(App, Menu, "Renders")
Rel(App, Foter, "Renders")
Rel(Menu, Pizza, "Renders multiple")
Rel(Foter, Order, "Conditionally renders")  
Rel(Pizza, PizzaData, "Reads from")

@enduml