# Generated by Django 5.0.7 on 2024-08-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
