# Generated by Django 5.0.7 on 2024-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='media/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
