# Generated by Django 5.0.7 on 2024-08-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Humans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='address',
            new_name='city',
        ),
    ]
