# Generated by Django 5.0.7 on 2024-08-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Humans', '0002_rename_address_human_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='human',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
