# Generated by Django 5.0.7 on 2024-08-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='continued_text',
            new_name='content',
        ),
    ]
