@startuml
component App 
    component NavBar
    component Logo
    component Search
    component NumResults

    frame "Box left" {
        component MoviesList
        component Movie
    }

    frame "Box right" {
        component MovieDetails
        component PrintMovieDetails
        component StarsRating
        component Stars

        component WatchedMovieList
        component WatchedSummary
        component WatchedMovie
    }




database omdbapi
App --> omdbapi
MovieDetails --> omdbapi

App --> NavBar
NavBar *-- Logo
NavBar --> Search
NavBar --> NumResults
App --> MoviesList
MoviesList *-- Movie
App --> MovieDetails
MovieDetails --> PrintMovieDetails
PrintMovieDetails *-- StarsRating
StarsRating *-- Stars
App --> WatchedSummary
App --> WatchedMovieList
WatchedMovieList --> WatchedMovie
@enduml